      *ESTE COPY SE UTILIZA PARA ACCEDER A LOS EMPLEADOS MEDIANTE SU PK (EMPLEADOS-ID),
      *ESPECIFICAR QUE SE VA A CREAR UN ARCHIVO INDEXADO AL CUAL SE LE ESTABLECERA EL NOMBRE "EMPLEADOS.DAT"
      *EL CUAL TENDRA UN TIPO DE ACCESO DINAMICO
       SELECT EMPLEADOS
       ASSIGN TO "EMPLEADOS.DAT"
        ORGANIZATION IS INDEXED
        RECORD KEY IS EMPLEADOS-ID

        ACCESS MODE IS DYNAMIC.
